spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.160.227:3306/hope?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: houzhenguo
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    filters: stat,wall,slf4j